services:
  # Directus service
  directus:
    labels:
      - org.clic.type=directus
    image: directus/directus:10
    user: ${UID}:${GID}
    environment:
      SECRET: secret
      KEY: key
      DB_CLIENT: postgres
      DB_HOST: directus-postgres
      DB_PORT: 5432
      DB_DATABASE: directus_data
      DB_USER: directus_user
      DB_PASSWORD: directus_pw

      EMAIL_VERIFY_SETUP: "true"
      EMAIL_FROM: it.clic@epfl.ch
      EMAIL_TRANSPORT: smtp

      EMAIL_SMTP_HOST: mail.epfl.ch
      EMAIL_SMTP_PORT: "587"
      EMAIL_SMTP_USER: it.clic
      EMAIL_SMTP_PASSWORD: ${SMTP_IT_PASSWORD}
      EMAIL_SMTP_SECURE: "false"
      EMAIL_SMTP_NAME: Directus

      PUBLIC_URL: http://localhost/directus
      ROOT_REDIRECT: /directus/admin
      ADMIN_EMAIL: clic@epfl.ch
      ADMIN_PASSWORD: 1234
    depends_on:
      - directus-postgres
    volumes:
      - .:/share
      - ./uploads:/directus/uploads
      - directus-extensions:/directus-extensions

  # Database for directus
  directus-postgres:
    labels:
      - org.clic.type=directus-postgres
    image: postgres
    environment:
      POSTGRES_DB: directus_data
      POSTGRES_USER: directus_user
      POSTGRES_PASSWORD: directus_pw
    volumes:
      - "directus-data:/var/lib/postgresql/data"

volumes:
  # Persist directus database
  directus-data:
  directus-extensions:
