services:
  # Directus service
  directus:
    labels:
      - org.clic.type=directus
    image: directus/directus:11.1.2
    user: ${UID}:${GID}
    hostname: directus
    environment:
      SECRET: secret
      KEY: key
      DB_CLIENT: postgres
      DB_HOST: database
      DB_PORT: 5432
      DB_DATABASE: directus_data
      DB_USER: directus_user
      DB_PASSWORD: directus_pw
      PUBLIC_URL: http://localhost/directus
      ROOT_REDIRECT: /directus/admin
      ADMIN_EMAIL: clic@epfl.ch
      ADMIN_PASSWORD: 1234
    depends_on:
      - directus-postgres
    volumes:
      - .:/share
      - ./uploads:/directus/uploads
      - directus-extensions:/directus-extensions

  # Database for directus
  directus-postgres:
    labels:
      - org.clic.type=directus-postgres
    image: postgres
    hostname: database
    environment:
      POSTGRES_DB: directus_data
      POSTGRES_USER: directus_user
      POSTGRES_PASSWORD: directus_pw
    volumes:
      - "directus-data:/var/lib/postgresql/data"

volumes:
  # Persist directus database
  directus-data:
  directus-extensions:
